#!/usr/bin/env bash
# This script moves a file from one server to another

if [ -z "$4" ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

scp -i "$4" "$1" "$3"@"$2":~/
