#!/usr/bin/env bash
# Setting up a web server
# make sure you run the file with sudo priviledges

# update and upgrade the shell
apt update -y && sudo apt upgrade -y

# install nginx
apt install nginx -y

# adjust the fire wall
ufw allow 'Nginx HTTP'

# set it up to match the requirment
echo 'Hello World!' > ~/new
cp ~/new /var/www/html/index.nginx-debian.html

# create a redirect link
string="server_name _;\n\trewrite ^/redirect_me(.*)$ google.com permanent;\n\n\terror_page 404 /custom_404.html;\n"
sed -i "s|server_name _;|$string|" /etc/nginx/sites-available/default

# restart nginx
service nginx restart
