#!/usr/bin/env bash
# Setting up a web server
# make sure you run the file with sudo priviledges

# update and upgrade the shell
apt update -y && sudo apt upgrade -y

# You need to enable a dedicated PPA with the following command
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6

# install the latest version of haproxy using:
apt-get install haproxy=2.6.\*

# We need to enable the HAProxy init script, so HAProxy will start and stop along with your VPS
# Change the value of ENABLED to 1 to enable the HAProxy init script:
echo 'ENABLED=1' >> /etc/default/haproxy

# setup the loadbalancer
echo "
frontend main-lb
	bind *:80
	mode http
	option http-server-close

	default_backend web-backend

backend web-backend
	balance roundrobin
	server web1 100.26.173.91:80 check
	server web2 54.90.46.131:80 check
" >> /etc/haproxy/haproxy.cfg

# restart haproxy
service haproxy restart
