#!/usr/bin/env bash
# loops from 1 to 10 and:
#	displays bad luck from china for the 4th loop iteration
#	displays good luck from japan for the 8th loop iteration
#	displays 'bad luck from Italy' for the 17th loop iteration

for i in {1..20}; do
	echo $i
	case $i in 
		4 )
		echo "bad luck from china"
		;;
	9 )
		echo "good luck from Japan"
		;;
	17 )
		echo "bad luck from Italy"
		;;
esac
done
