#!/usr/bin/env bash
# Run nginx as `nginx` user

# grant the root user write permission
sudo chmod u+wrx /etc/nginx/nginx.conf

# change the user
echo 'user nginx;' >> /etc/nginx/nginx.conf

# give proper permission to nginx user to access the
# file (affects all users)
sudo chmod +r /etc/nginx/nginx.conf

string="http {\n\tserver {\n\t\tlisten 0.0.0.0:8080;\n\t}"
sed -i "s|http {|$string|" /etc/nginx/nginx.conf

# run as nginx user
sudo -u nginx service nginx start
