#!/usr/bin/env bash
# Run nginx as `nginx` user

pkill apache2
# grant the root user write permission
sudo chmod u+wrx /etc/nginx/nginx.conf

# change the user
sed -i "s|#user www-data|user nginx|" /etc/nginx/nginx.conf

# give proper permission to nginx user to access the
# file (affects all users)
chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 0644 /etc/nginx/nginx.conf

# make nginx listen on port 8080
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default

# run as nginx user
sudo -u nginx service nginx start
