#!/usr/bin/env bash
# Run nginx as `nginx` user
pkill apache2
sudo chmod 0644 /etc/nginx/nginx.conf
sed -i "s|#user www-data|user nginx|" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
